name: iOS CI - Build IPA

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: macos-14
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Generate Xcode Project
        working-directory: TasksApp
        run: xcodegen generate

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Cache SPM
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData
            ~/Library/Caches/org.swift.swiftpm
            ~/Library/Developer/Xcode/Archives
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}

      - name: Resolve SPM
        working-directory: TasksApp
        run: |
          xcodebuild -resolvePackageDependencies -project TasksApp.xcodeproj -scheme TasksApp

      - name: Build archive (unsigned)
        working-directory: TasksApp
        run: |
          set -euo pipefail
          xcodebuild \
            -project TasksApp.xcodeproj \
            -scheme TasksApp \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $PWD/build/TasksApp.xcarchive \
            clean archive \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGNING_IDENTITY=""

      - name: Export IPA (ad-hoc unsigned)
        working-directory: TasksApp
        run: |
          set -euo pipefail
          mkdir -p build/export
          xcodebuild -exportArchive \
            -archivePath $PWD/build/TasksApp.xcarchive \
            -exportPath $PWD/build/export \
            -exportOptionsPlist <(cat <<'PLIST'
            <?xml version="1.0" encoding="UTF-8"?>
            <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
            <plist version="1.0">
            <dict>
              <key>method</key>
              <string>ad-hoc</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>compileBitcode</key>
              <false/>
              <key>destination</key>
              <string>export</string>
              <key>stripSwiftSymbols</key>
              <true/>
            </dict>
            </plist>
            PLIST
            ) \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGNING_IDENTITY=""

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TasksApp-unsigned-ipa
          path: TasksApp/build/export/*.ipa
          if-no-files-found: warn
